steps:
  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/terratest', '--build-arg', 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}' ,'.']

images:
- 'gcr.io/$PROJECT_ID/terratest:latest'

timeout: 3600s
substitutions:
  _TERRAFORM_VERSION: 0.13.0

