- hosts: all
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install packages for installing docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: register apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: get os version
      command: lsb_release -cs
      register: os_version

    - name: add apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_version.stdout }} stable

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
