steps:
  - id: 'terraform workspace select'
    name: 'alpine/terragrunt'
    args: ['run-all', 'workspace', 'select', 'prd']
    env:
      - 'SKIP_OUTPUT=true'

  - id: 'terragrunt destroy'
    name: 'alpine/terragrunt'
    args: ['run-all', 'destroy', '--terragrunt-non-interactive']
    env:
      - 'SKIP_OUTPUT=false'
