kind: Pod
apiVersion: v1
metadata:
  name: sample-pvc-pod
spec:
  containers:
    - name: nginx-containers
      image: nginx
      ports:
        - containerPort: 80
          name: "http"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-pvc
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: sample-pvc
