apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-smp3
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  {{ if eq .Values.favorite.drink "coffee" }}mug: true {{ end }}
  {{- if eq .Values.favorite.drink "coffee" }}
  beans: true
  {{- end }}
  {{ if eq .Values.favorite.drink "tea" }}hoge: true {{ end }}
