apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-smp4-with-sample
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $.Release.Name }}
  {{ end }}
