apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-smp6
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $relname }}
  {{- end }}
  toppings: |-
    {{- range $index, $topping := .Values.pizaToppings }}
    {{ $index }}: {{ $topping }}
    {{- end }}
