apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-smp2
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
