apiVersion: v1
kind: Service
metadata:
  name: neg-demo-sv
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  selector:
    app: neg-demo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
