steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']

- name: 'gcr.io/cloud-builders/yarn'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']
